[workspace]
authors = ["obi <ole.bialas@posteo.de>"]
channels = ["conda-forge"]
name = "Introduction-to-Scientific-Data-Management-with-DataLad"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
ipykernel = "*"

[pypi-dependencies]
datalad = ">=1.2.3, <2"
datalad-next = ">=1.5.0, <2"
git-annex = ">=10.20250721, <11"
ipykernel = "*"
